#!/bin/bash
touch my_putchar.c
touch my_isneg.c
touch my_isneg.c
touch my_swap.c
touch my_putstr.c
touch my_strlen.c
touch my_getnbr.c
touch my_sort_int_array.c
touch my_compute_power_rec.c
touch my_compute_square_root.c
touch my_is_prime.c
touch my_find_prime_sup.c
touch my_strcpy.c
touch my_strncpy.c
touch my_revstr.c
touch my_strstr.c
touch my_strcmp.c
touch my_strncmp.c
touch my_strupcase.c
touch my_strlowcase.c
touch my_strcapitalize.c
touch my_str_isalpha.c
touch my_str_isnum.c
touch my_str_islower.c
touch my_str_isupper.c
touch my_str_isprintable.c
touch my_showstr.c
touch my_showmem.c
touch my_strcat.c
touch my_strncat.c